### PR TITLE
Removed duplicated code and added a few unit tests.

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by shawnfeldman** [comment]
are you running solr? i would stay away from this code unless you are 100% positive it works

**Comment by shawnfeldman** [comment]
you'd have to guarantee TOLEADER calls don't happen

**Comment by shawnfeldman** [comment]
if you aren't sure what that is i'd stay away from changing any bit shifting logic

**Comment by tariq1890** [comment]
So for this change, I wrote hash_test.go first and then changed the Hash method. This is to provide assurance that only the code has been changed while keeping the bit-shifting logic intact.

**Comment by tariq1890** [comment]
I am using a containerized solr image. The go-solr code connects to that.

**Comment by shawnfeldman** [comment]
i'm hesitant to change this code at all even though this looks fine.  This doesn't seem to add any value other than a sleight refactor for a few lines of code

**Pull request merged**
